### ISSUE TITLE
Scanln usage

### ISSUE THREAD

**Issue by Sddilora** [johsquaree/goo#1]
The issue you're encountering in the fmt.Scanln function's requirements on the code located at https://github.com/johsquaree/goo/blob/master/little-ai/wtf.go is related to its expectation for a newline character. The package's documentation states that "Scanln is similar to Scan, but stops scanning at a newline, and after the final item, there must be a newline or EOF."

To address this problem, you can resolve it by introducing a newline character into the input stream. One way to achieve this is by using the bufio package, which is specifically designed for handling buffered input. Below is an improved version of the code with an explanation:
```go
func main() {
	fmt.Println("Ask me anything. If you want to exit, simply type 'exit'.")

	var response string
	var question string

	// Create a bufio reader for standard input
	reader := bufio.NewReader(os.Stdin)

	for {
		fmt.Print("Question: ")
		fmt.Scanln(&question) // Scan the user's input

		// Read and discard the newline character from the input stream
		reader.ReadString('\n')

		if question == "exit" {
			fmt.Println("See you later.")
			break
		}

		response = getRandomResponse()
		fmt.Printf("Answer: %s\n", response)
	}
}
```

In this improved version of the code, we create a bufio.Reader to handle standard input, and after scanning the user's question, we use reader.ReadString('\n') to read and discard the newline character, ensuring that subsequent Scanln calls work as expected. This modification should resolve the issue you mentioned.

**Comment by Sddilora** [comment]
It is stiil cause problem, in tech forms they recommend to use buffer's scanner.

**Comment by johsquaree** [comment]
i made the requested changes and i fixed this problem.
